### ISSUE TITLE
Fascinante

### ISSUE THREAD

**Issue by cHIsIMun** [JoaoSenirio/LEGOEV3_Sensors_NewUsability#1]
Olá, trabalho com robótica aplicada e estou inserido nesse meio há bastante tempo, gosto muito de projetos como este de integrações, projetos que extraem coisas incríveis de componentes do nosso dia-a-dia, gostaria de fazer um contato maior para troca de experiências, há alguma rede social em que possamos discutir assuntos desta área? Seu projeto está excepcional, de ponta a ponta, sua documentação está impecável, meus parabéns!

**Comment by JoaoSenirio** [comment]
Olá, boa tarde Lucas!
Fico feliz que tenha gostado do que viu no repositório. Esse é um projeto
muito especial para mim e pretendo aperfeiçoá-lo, apesar da falta de tempo
livre para tal. Pode me chamar no WhatsApp (31)999033520 para trocarmos
experiência. Te aguardo!

Desde já agradeço,
João Senírio.

Em qui., 16 de mar. de 2023 11:18, Lucas Vinicius ***@***.***>
escreveu:
